# Site settings
title: Thomas Read
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: https://github.com/Thomasread04/thomasread04.github.io

# User settings
username: Thomas Read
user_description: I'm a full time high school student with a passion for learning about computers, carpentry, and self sufficient living.
email: thomasread04@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
